### ISSUE TITLE
Editor’s error while navigating the patterns menu

### ISSUE THREAD

**Issue by ericvalois** [blocknotes-org/blocknotes#1]
![IMG_1041](https://github.com/ellatrix/blocknotes/assets/7623388/a5fe10ad-d39a-44f6-b4a9-b62de8800fcd)

**Comment by ellatrix** [comment]
Yeah, @adamziel reported this one to me too. I might disable the patterns library for now. Considering this low priority as I'm just trying to get the basics right first.

**Comment by adamziel** [comment]
It is weird that this seems to work on playground.wordpress.net

**Comment by ellatrix** [comment]
This is not an issue right now, after the rewrite.
