### ISSUE TITLE
Website error

### ISSUE THREAD

**Issue by carstingaxion** [blocknotes-org/blocknotes#15]
Hello @ellatrix ,

unfortunately I got an error, when visiting the website from an iPadOs 17.5.1 with Firefox.

![IMG_0175](https://github.com/blocknotes-org/blocknotes/assets/198883/ea58448d-bc33-4457-a2f0-94422fa3a3e4)

I was curious and wanted to learn about and test blocknotes.

**Comment by ellatrix** [comment]
Yes, this is normal, the only supported browser right now are Chromium based browsers (Chrome, Opera, Edge etc.)
At some point I'll update the landing page with a more helpful note.

**Comment by carstingaxion** [comment]
Thank you for your fast response.

Ok, I see, trying to test a PWA with Firefox, seems to be not a good idea at all.

But I was experiencing the same at first with Vivaldi and after that also with Chrome. Both fresh installs.
![image](https://github.com/blocknotes-org/blocknotes/assets/198883/091e789c-01a4-46de-a57a-8aa86c37cb90)
![image](https://github.com/blocknotes-org/blocknotes/assets/198883/75e3645a-730c-4955-bf22-6b2b9b30867e)

I'm not sure, but this might be because of Apple not allowing real third party browsers (until recently). And because of my "old" device, I still have the safari-based versions of those browsers. I don't know.

**Comment by ellatrix** [comment]
@carstingaxion Unfortunately, there are no browsers that support the API on mobile, not even Chrome. 
On mobile, it only works with the app: https://apps.apple.com/us/app/blocknotes/id6450189974

**Comment by ellatrix** [comment]
I've updated https://blocknotes.org with a more helpful text.

**Comment by carstingaxion** [comment]
Thank you for answering all my questions. The new homepage is what people like me, will like for sure. Thanks.
