### ISSUE TITLE
TypeError thrown when bringing app to the foreground with an empty note

### ISSUE THREAD

**Issue by twstokes** [blocknotes-org/blocknotes#18]
1. Start a new note
2. Switch to another app or the Home Screen
3. Bring Blocknotes back to the foreground
4. Observe the TypeError thrown and a reset of the editor

Blocknotes v1.2 / iPhone 12 / iOS 17.4.1

https://github.com/user-attachments/assets/9211c1dd-0505-46ae-8bb5-3420c6a55c0d

**Comment by ellatrix** [comment]
Thanks!
