### ISSUE TITLE
Invalid blocks are able to be inserted

### ISSUE THREAD

**Issue by twstokes** [blocknotes-org/blocknotes#20]
1. Start a new note
2. Tap the block inserter button **+**
3. Search for a block such as Archives
4. Select the block
5. Observe an error

Blocknotes v1.2 / iPhone 12 / iOS 17.4.1

https://github.com/user-attachments/assets/2ae79b31-d9a9-4432-b351-8c36d805562d

**Comment by ellatrix** [comment]
Thanks! All non basic blocks were removed in 4ae89b72e8785c0c6c70e0442f615a1099b27ab3.
