### ISSUE TITLE
Accessibility: VoiceOver incorrectly says that images can be inserted from media library

### ISSUE THREAD

**Issue by twstokes** [blocknotes-org/blocknotes#24]
1. Enable VoiceOver
2. Start a new note
3. Add an image block
4. Observe VoiceOver say that images can be inserted from the media library when there is [currently no support](https://github.com/blocknotes-org/blocknotes/issues/23)

Blocknotes v1.2 / iPhone 12 / iOS 17.4.1

https://github.com/user-attachments/assets/b923585e-9481-4832-b7a8-149df923c6ea

**Comment by ellatrix** [comment]
Remove the block in 4ae89b72e8785c0c6c70e0442f615a1099b27ab3, let's use the other issue for the feature request.
